name: 'Export Images'
description: 'Export Image files from a Kicad PCB'
inputs:
  pcb_file:
    description: 'Kicad input file'
    required: true
  image_dir:
    description: 'Image output folder'
    required: true
runs:
  using: 'docker'
  image: 'docker://yaqwsx/kikit:v0.7'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      mkdir -p $GITHUB_WORKSPACE/${{ inputs.image_dir }} ;
      pcbdraw --style builtin:set-white-enig.json $GITHUB_WORKSPACE/${{ inputs.pcb_file }} $GITHUB_WORKSPACE/${{ inputs.image_dir }}/left.png
      pcbdraw -b --style builtin:set-white-enig.json $GITHUB_WORKSPACE/${{ inputs.pcb_file }} $GITHUB_WORKSPACE/${{ inputs.image_dir }}/right.png
